aminohealth/phenotypes

- components/css_spacing_utilities/README.md
- components/grid/grid.jsx
- components/message/_message.scss
- fractal_assets/css/preview.css
- styles/_variables.scss
- styles/phenotypes.css
- styles/utilities/_spacing.scss
Changes:
* Added `mxn[size]-[breakpoint]` negative margin x-axis helpers to reach parity with Basscss's approach to customizing grid gutters (need to add them to the parent `.row` class to get rid of extra side padding)
* Grid examples now makes more sense: <br><img width="400" alt="screen shot 2017-07-06 at 11 42 39 am" src="https://user-images.githubusercontent.com/396006/27927318-3ca75c02-6240-11e7-97b3-aca9a36bf626.png">
* Added background color for base `.Message` class
* Customized `$container-max-widths` for grid container widths
> Grid followup tweaks

- fractal_assets/css/preview.css
- fractal_react/__components.js
- library/components/button/_button.scss
- library/components/checkbox/_checkbox.scss
- library/components/form_group/_form_group.scss
- library/components/text_input/_text_input.scss
- library/utilities/flexbox/_flexbox.scss
- library/utilities/flexbox/flexbox.jsx
- library/utilities/sizing/README.md
- library/utilities/sizing/_sizing.scss
- library/utilities/sizing/sizing.config.json
- library/utilities/sizing/sizing.jsx
- library/utilities/spacing/README.md
- library/utilities/spacing/_spacing.scss
- library/utilities/typography/_typography.scss
- library/utilities/typography/typography.jsx
- styles/_features.scss
- styles/_utilities.scss
- styles/phenotypes.css
Brings some utilities over from pare_web that I think will be commonly used enough to be here.
- sizing utilities, such as `.width5`, `.height3-sm` and also some 100% utils like `.width-full` and `.height-full`.
- negative margin classes (e.g. `mtn3`)
- `.text-underline`
- `.flex-none`, for specifying that an item in a flexbox should not shrink or grow. Basscss has this class.
cc @sumul
> Add more utilities

- styles/_components.scss
- styles/_utilities.scss
@iqnivek I changed these import paths when I did the component reorg, without realizing that it would break things when another project (like pare_web) tries to compile the css.
> Fix scss compilation in other projects

- library/components/checkbox/README.md
- library/components/checkbox/checkbox.jsx
- library/components/checkbox/checkbox.spec.jsx
We ended up just using the `:disabled` state on the checkbox element to apply the disabled style, which I think was the right call, because:
- we also apply styling with `:checked` and `:active`
- it seems unlikely that we'd want to apply the disabled style without actually disabling the checkbox (and that would probably be confusing for the user anyway)
cc @iqnivek
> Remove .Checkbox—is-disabled modifier

- library/components/button/anchor_button.jsx
@gelsto 
Didn't realize that calling setState without any actual changes will call `render` again anyway ... if you hold down spacebar, the keydown event can be triggered many, many times. This will avoid re-rendering many, many times.
> Don’t re-render unless actually need to apply active class

- guides/04-color.md
- library/utilities/grid/grid/_grid.scss
- styles/phenotypes.css
This came about because Sumul's sketch files have 16px left/right margins, and we want to have the container default line up with that.
> Update .container's left/right padding to be 16px (up from 12px)

- library/components/button/_button.scss
- library/utilities/typography/_typography.scss
- library/utilities/typography/typography.jsx
- package.json
- styles/_reboot.scss
- styles/_variables.scss
- styles/mixins/_type.scss
- styles/phenotypes.css
- adds `-webkit-font-smoothing: antialiasing` and `-moz-osx-font-smoothing: grayscale;` (for firefox) to the `<body>`. The non-vendor-prefixed `font-smooth` property doesn't appear to do anything (I tried in all the main browsers), so left that out.
- adds text color utilities, with docs
- the `reversed-text` mixin has been removed (it was mainly adding antialiasing for reversed text, which is no longer necessary)
- antialiasing of text is kinda breaking? since the style of all text is slightly changing
> Font antialiasing and text-color utilities

- library/components/button/README.md
- library/components/button/_button.scss
- library/components/button/button.spec.jsx
- library/components/text_input/text_input.spec.jsx
- styles/phenotypes.css
This adds `width: 100%` to the `Button__control` class so the inner button or anchor element will expand to the size of its wrapping `Button` div.
We could consider adding something like `height: inherit` to `Button__control` as well, but I don't see any reason we'd set the height outside of the button sizing classes currently.
Also updated the tests and the button docs usage section.
> Add support for setting the width of buttons with our normal sizing classes

- package.json
- styles/phenotypes.css
- yarn.lock
See https://github.com/sass/node-sass/issues/2676
Our node-sass version is the same, I just uninstalled/reinstalled it at the pinned version
> Get fstream 1.0.12 as node-sass dep

- library/components/radio/_radio.scss
- styles/phenotypes.css
The text was a little too close to the radio on small/medium versions. Updated to use the same spacing as checkboxes.
> Fix spacing on small/medium radios

- library/utilities/sizing/_sizing.scss
- styles/_variables.scss
- styles/phenotypes.css
I want to be able to do this in web:
```jsx
<div className="height-12 height-auto-sm">
```
But that doesn't work, because `height-12` is defined in web, so it's more specific than `height-auto-sm` which is defined in phenotypes and thus comes earlier in the stylesheet.
I'm only adding these sizes to our height/width utilities (not our margin, padding, etc. utilities), so it's not a huge addition.
> Add more sizes (10, 11, 12, 13)

- Dockerfile
- package.json
- styles/phenotypes.css
- yarn.lock
@sumul @NickDunkman this PR upgrades the base docker image used to build this project from `node:boron` to `node:12.6.2-stretch-slim`. `node:boron` appears to be several years out-of-date. We also plan to upgrade pare_web's `www_js` container to that same base image for node 12.
node-sass `4.12+` is required to use node 12, so I upgraded node-sass from `4.5.3` to `4.13.1`. The latest release is `4.14` but that was published just this week, so I figured `4.13.1` would be a little more stable.
After making the dependency changes I was able to build, test, and run the `fractal` container just fine. Is there anything else I can do to validate that these upgrades don't cause any issues downstream?
> Upgrade to node 12 and bump node-sass dependency

- README.md
- THEMING.md
- fractal_assets/css/phenotypes.themable.css
- guides/06-spacing.md
- guides/11-theming.md
- library/_preview.jsx
- library/components/button/_button.scss
- library/components/checkbox/_checkbox.scss
- library/components/form_group/_form_group.scss
- library/components/message/_message.scss
- library/components/progress_bar/_progress_bar.scss
- library/components/radio/_radio.scss
- library/components/slider/_slider.scss
- library/components/switch/_switch.scss
- library/components/text_input/_text_input.scss
- library/utilities/spacing/README.md
- library/utilities/typography/_typography.scss
- package.json
- scripts/compileScss.js
- scripts/copyLibraryAssets.js
- styles/_mixins.scss
- styles/_reboot.scss
- styles/_theme_config.scss
- styles/mixins/_color.scss
- styles/phenotypes.css
- styles/phenotypes.scss
- styles/phenotypes.themable.css
- yarn.lock
looks like a lot, but if you ignore the generated css files that we are checking in (of which there are two, both at 6177 lines) there around 350 lines worth of changes in here.
Changes included in this pr:
* Adds a `_theme_config.scss` file which contains a `:root` rule containing all of the themable variable declarations
* Updates the build script to compile two different css files, one with css variables included and one without. (this adds a postcss dependency to the build. post-css is used to strip away the css variables for the non-variable build)
* Updates the react components to use the theme variables
* Updates a few utility classes to use the theme variables
* Updates the phenotypes fractal website to use the themable css file. (This breaks IE11 compatibility)
* Updates the …
> Add initial support for theming via variables

- fractal_assets/css/phenotypes.themable.css
- library/utilities/spacing/_spacing.scss
- styles/phenotypes.css
- styles/phenotypes.themable.css
So we have an issue in pare_web where a component like this ...
```jsx
<div className="p5 p6-sm pt5-sm" />
```
... ignores that `pt5-sm` because that class is higher up than `p6-sm` (less specific) in the phenotypes code.
In other words, your layout should look like this:
```
tiny              small
24                [24]
24    24           36    36
24                 36
```
Instead of this:
```
tiny              small
24                [36]
24    24           36    36
24                 36
```
To fix, I did some re-ordering of the spacer rules. I don't think this will cause much disruption to layouts in pare_web, but will do look-through the app when bumping web to use this change. After this change, the rules are ordered like this:
```
===== default ======
m0 m1 m2 m3 m4 m5 m6 m7 m8 m9 …
```
> Fix spacer specificity

- package.json
Releasing the changes to specificity of spacer rules made [here](https://github.com/aminohealth/phenotypes/pull/100) as a patch.
> Bump to version 8.0.1

- fractal_assets/css/phenotypes.themable.css
- guides/11-theming.md
- library/components/checkbox/_checkbox.scss
- library/components/progress_bar/_progress_bar.scss
- library/components/radio/_radio.scss
- library/components/slider/_slider.scss
- library/components/text_input/_text_input.scss
- styles/_reboot.scss
- styles/_theme_config.scss
- styles/phenotypes.themable.css
Adds a few extra variables to make focus glow opacities themable. This will be helpful especially when we want to disable the glow for certain themes. The variables are listed below:
* `--step-progress-active-glow-opacity`
* `--text-input-glow-opacity`
* `--checkbox-focus-glow-opacity`
* `--checkbox-checked-focus-glow-opacity`
* `--radio-focus-glow-opacity`
* `--radio-checked-focus-glow-opacity`
* `--slider-focus-glow-opacity`
Also adds a `--font-family` variable to make font family themable.
> Make focus glow opacity and font family themable

- guides/01-index.md
- guides/02-modular-scale.md
- guides/03-typography.md
- guides/04-color.md
- guides/05-logo.md
- guides/06-spacing.md
- guides/07-layout.md
- guides/08-icons.md
- guides/09-depth-shadows.md
- guides/10-data-visualization.md
- guides/11-theming.md
- library/components/button/README.md
- library/components/checkbox/README.md
- library/components/form_group/README.md
- library/components/progress_bar/README.md
- library/components/radio/README.md
- library/components/slider/README.md
- library/components/switch/README.md
- library/components/tab/README.md
- library/components/text_input/README.md
- library/utilities/display/README.md
- library/utilities/flexbox/README.md
- library/utilities/sizing/README.md
- library/utilities/spacing/README.md
- library/utilities/typography/README.md
A recent update caused some of the markdown tables to be broken when rendered in the phenotypes documentation website. Reformatting the markdown files with prettier fixes the issue, so I went ahead and applied prettier formatting to all of the relevant markdown files. After testing locally, all markdown files seem to be rendered correctly.
> Reformat all markdown files with prettier

- configs/rollup.phenotypes-library.config.js
- fractal_assets/css/phenotypes.themable.css
- library/components/checkbox/_checkbox.scss
- library/components/radio/_radio.scss
- library/components/slider/_slider.scss
- styles/_theme_config.scss
- styles/phenotypes.css
- styles/phenotypes.themable.css
This pr does two things:
When we added theming support, a few form element border-color declarations were missed in the conversion to use theming variables. This fixes that bug.
I also added source maps for the compiled outputs since it was as simple as adding a flag and will help with debugging the compiled output if the need arises.
Prettier also formatted a few of these files so the changes look a bit bigger than they actually are.
> Update form elements to have themable borders + add sourcemaps

- library/components/form_group/form_group.jsx
Fix accessibility issues related to error messages
```
The error messages on forms show visibly but are not programmatically associated with the text field potentially causing users to not understand how to complete the forms. 
```
this shows how the `aria-errormessage` is getting the proper id:
screen reader alerting "required" once the `save` button is clicked:
more info on `aria-errormessage: [https://www.w3.org/TR/wai-aria-1.1/#aria-errormessage](https://www.w3.org/TR/wai-aria-1.1/#aria-errormessage)
> add aria to associate error with form

- fractal_assets/css/phenotypes.themable.css
- library/components/button/_button.scss
- styles/phenotypes.css
- styles/phenotypes.themable.css
Updates the primary color and error color buttons to have a 1px border of the same color, to keep the height the same as the already bordered secondary buttons
> Border sizing fix for buttons

- configs/rollup.fractal-development.config.js
- fractal_assets/css/phenotypes.themable.css
- library/components/slider/_slider.scss
- library/components/switch/_switch.scss
- library/components/tab/_tab.scss
- library/utilities/grid/grid/_grid.scss
- package.json
- scripts/compileScss.js
- styles/_modular-scale.scss
- styles/lib/_pow.scss
- styles/mixins/_depth.scss
- styles/phenotypes.css
- styles/phenotypes.themable.css
- yarn.lock
`node-sass` is deprecated and does not run on the new Apple silicon! The node-sass people [say to upgrade to "dart" sass](https://sass-lang.com/blog/libsass-is-deprecated), which is just called `sass`.
With this change, phenotypes can now be built & run on the new m1 chips.
A couple trivial changes:
- the `/` operator is deprecated in dart sass -- had to convert them all to use `math.div`
- there are a bunch of changes in the compiled css files, but they're all just replacing single quotes with double quotes, and whitespace changes.
> Replace deprecated node-sass with sass

- package.json
Pushing out the node-sass -> sass conversion so that anything that uses phenotypes isn't blocked from working with apple silicon.
This also adds a few dependency security patches added by @dependabot.
> Bump to version 11.0.2
